CFLAGS		= -std=c89 -g -w -m32

icint:		icint.o interp.o sub.o
		$(CC) $(LDFLAGS) $(CFLAGS) -o $@ icint.o interp.o sub.o

icint.o:	icint.c icint.h

interp.o:	interp.c icint.h

sub.o:		sub.c icint.h

clean:
	rm *.o icint

# XXX fails
test:
	./icint -v fact.int
	./icint -v cg.int
